- id: '1684422694124'
  alias: sunSetLedEntrataON
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_on
    device_id: 0fd83799c9d1f093e3684d436c4614cb
    entity_id: switch.ledout
    domain: switch
  mode: single
- id: '1684508590238'
  alias: sunSetLedEntrataOFF
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '2:20'
  condition: []
  action:
  - type: turn_off
    device_id: 0fd83799c9d1f093e3684d436c4614cb
    entity_id: switch.ledout
    domain: switch
  mode: single
- id: '1688424518679'
  alias: timerBoilerStart
  description: ''
  trigger:
  - platform: time
    at: input_datetime.boiler_start
  condition: []
  action:
  - type: turn_on
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1688424544929'
  alias: timerBoilerStop
  description: ''
  trigger:
  - platform: time
    at: input_datetime.boiler_stop
  condition: []
  action:
  - type: turn_off
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1689597287797'
  alias: boilerFirstStageON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_minus05_enel_plus1_solar
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1689597312837'
  alias: boilerFirstStageOFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_minus05_enel_plus1_solar
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.manualboiler
    state: 'off'
  action:
  - type: turn_off
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1684411816150'
  alias: mumEnterHome
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.enrica_s_phone
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: 69087beaa9402f84b5280c5a705f7621
    domain: mobile_app
    type: notify
    message: Mum enter home
  - device_id: ca685c3b3eef896822f021d3153787f6
    domain: mobile_app
    type: notify
    message: Mum enter home
  mode: single
- id: '1684443772730'
  alias: dadEnterHome
  description: ''
  trigger:
  - platform: zone
    entity_id: person.adriano
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: 69087beaa9402f84b5280c5a705f7621
    domain: mobile_app
    type: notify
    message: Dad enter home
    title: Dad
  - device_id: ca685c3b3eef896822f021d3153787f6
    domain: mobile_app
    type: notify
    message: Dad enter home
  mode: single
- id: '1691699008243'
  alias: iPad20PercentTurnON
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: ede330a4d1d8b3aa4ce2a3f7fbf86bb2
    entity_id: ef916e116aeacdcb2b74fedbc315d722
    domain: sensor
    below: 20
  condition:
  - condition: device
    type: is_off
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  action:
  - type: turn_on
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- id: '1691699042947'
  alias: iPad80PercentTurnOFF
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: ede330a4d1d8b3aa4ce2a3f7fbf86bb2
    entity_id: ef916e116aeacdcb2b74fedbc315d722
    domain: sensor
    above: 80
  condition: []
  action:
  - type: turn_off
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- id: '1692911680530'
  alias: camerasDetectionNotification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garden_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id: sensor.back_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id: sensor.gardensouth_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  condition:
  - condition: state
    entity_id: input_boolean.person_notification
    state: 'on'
  - condition: and
    conditions:
    - condition: device
      device_id: 69087beaa9402f84b5280c5a705f7621
      domain: device_tracker
      entity_id: a8a9b6ef0ada0f9b06fd36d970d4f3db
      type: is_not_home
    - condition: device
      device_id: f93e1ea2da204f999e9e38af4b77782b
      domain: device_tracker
      entity_id: 9c0c263dfc385d9cb344db0356665a30
      type: is_not_home
    - condition: device
      device_id: 3985d73a7a80bc86bc18415055134bf0
      domain: device_tracker
      entity_id: 795fcdd36be70af583a8e8329f6b3343
      type: is_not_home
  action:
  - device_id: 69087beaa9402f84b5280c5a705f7621
    domain: mobile_app
    type: notify
    message: Cameras
    title: Person detect
  mode: single
- id: '1692972394716'
  alias: frigateEntranceKito
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.entrance
      base_url: https://xc5oo1paki2zabddex3se0s8lcrq40ho.ui.nabu.casa/
      color: red
      message: Entrance person
      attachment: snapshot
      cooldown: 185
      tap_action: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
      notify_device: 69087beaa9402f84b5280c5a705f7621
      silence_timer: 8
      disable_times:
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
      - '15'
      - '16'
      - '17'
      - '18'
      - '19'
      - '20'
- id: '1694008677172'
  alias: FrigateEntranceDad
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.entrance
      base_url: https://xc5oo1paki2zabddex3se0s8lcrq40ho.ui.nabu.casa/
      color: red
      message: Entrance person
      attachment: snapshot
      cooldown: 185
      tap_action: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
      silence_timer: 8
      notify_device: 3985d73a7a80bc86bc18415055134bf0
      disable_times:
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
      - '15'
      - '16'
      - '17'
      - '18'
      - '19'
      - '20'
- id: '1694041188700'
  alias: EntrancePersonInNightLed
  description: 'when entrance camera detect person turn on for 3.14 minutes entrance
    led and lampade out


    v2

    for turn off now wait the trigger below1 person for 3.14 min, so if person reappen,
    it restart the counter of 3.14 min, '
  trigger:
  - type: value
    platform: device
    device_id: 7f18cc52a1f0db774bdf1ab808e3d624
    entity_id: 6d80ff481151fab8778752679f4a3d9a
    domain: sensor
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: 0:20
    before_offset: 0:30
  action:
  - type: turn_on
    device_id: 0fd83799c9d1f093e3684d436c4614cb
    entity_id: 2f584d1f082626498d31638040f00651
    domain: switch
  - type: turn_on
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: 7af0d52f2f672ccab6a06f04edbc3436
    domain: switch
  - wait_for_trigger:
    - type: value
      platform: device
      device_id: 7f18cc52a1f0db774bdf1ab808e3d624
      entity_id: 6d80ff481151fab8778752679f4a3d9a
      domain: sensor
      below: 1
      for:
        hours: 0
        minutes: 3
        seconds: 14
    timeout:
      hours: 0
      minutes: 3
      seconds: 14
      milliseconds: 0
  - type: turn_off
    device_id: 0fd83799c9d1f093e3684d436c4614cb
    entity_id: 2f584d1f082626498d31638040f00651
    domain: switch
  - type: turn_off
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: 7af0d52f2f672ccab6a06f04edbc3436
    domain: switch
  mode: single
- id: '1694689039662'
  alias: batterySecondStageON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_second_stage
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: device
    type: is_off
    device_id: e5c9f23f4ba4b34e7a163f258d5493c9
    entity_id: e70bc5233813107e15be0f35f3fb4dda
    domain: switch
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'off'
  action:
  - type: turn_on
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1694689062167'
  alias: batterySecondStageOFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_second_stage
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'off'
  action:
  - type: turn_off
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695148743588'
  alias: ledSwitchCameraBackDetect
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: d616f14b47ba4ebec4d453f5e8934b99
    entity_id: e56df8d79f1f6b0f906f001de2231a85
    domain: sensor
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: 0:10
  - condition: device
    type: is_off
    device_id: 35266dbd54cd05706885160a06fa6aa9
    entity_id: 65eb9d75dd1e12c0b5ae4939e3a2b54c
    domain: switch
  action:
  - type: turn_on
    device_id: 35266dbd54cd05706885160a06fa6aa9
    entity_id: 65eb9d75dd1e12c0b5ae4939e3a2b54c
    domain: switch
  - delay:
      hours: 0
      minutes: 3
      seconds: 14
      milliseconds: 0
  - type: turn_off
    device_id: 35266dbd54cd05706885160a06fa6aa9
    entity_id: 65eb9d75dd1e12c0b5ae4939e3a2b54c
    domain: switch
  mode: single
- id: '1695217201945'
  alias: ledBackCameraBackDetect
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: d616f14b47ba4ebec4d453f5e8934b99
    entity_id: 4abfcb69e2524780628c72669905cd2c
    domain: sensor
    above: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: c27acc2ccd63098e7b1bfdc348a38ab8
    domain: switch
  - delay:
      hours: 0
      minutes: 2
      seconds: 14
      milliseconds: 0
  - type: turn_off
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: c27acc2ccd63098e7b1bfdc348a38ab8
    domain: switch
  mode: single
- id: '1695389117202'
  alias: timerInvertSTART_1
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ininverter_start1
  condition:
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'on'
  action:
  - type: turn_on
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695389148468'
  alias: timerInvertSTART_2
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ininverter_start2
  condition:
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'on'
  action:
  - type: turn_on
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695389235327'
  alias: timerInvertSTOP_1
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ininverter_stop1
  condition:
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'on'
  action:
  - type: turn_off
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695389248826'
  alias: timerInvertSTOP_2
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ininverter_stop2
  condition:
  - condition: state
    entity_id: input_boolean.ininverter_manual
    state: 'on'
  action:
  - type: turn_off
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695390569590'
  alias: timerSwitchACboxSTOP
  description: ''
  trigger:
  - platform: time
    at: input_datetime.switchac_stop
  condition:
  - condition: state
    entity_id: input_boolean.manualbattery
    state: 'on'
  action:
  - type: turn_off
    device_id: e5c9f23f4ba4b34e7a163f258d5493c9
    entity_id: e70bc5233813107e15be0f35f3fb4dda
    domain: switch
  mode: single
- id: '1695390607787'
  alias: timerSwitchACboxSTART
  description: ''
  trigger:
  - platform: time
    at: input_datetime.switchac_start
  condition:
  - condition: state
    entity_id: input_boolean.manualbattery
    state: 'on'
  action:
  - type: turn_on
    device_id: e5c9f23f4ba4b34e7a163f258d5493c9
    entity_id: e70bc5233813107e15be0f35f3fb4dda
    domain: switch
  mode: single
