- id: '1689597287797'
  alias: boilerFirstStageON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_minus05_enel_plus1_solar
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.sunny_day
    state: 'on'
  - condition: state
    state: 'off'
    entity_id: input_boolean.manualboiler
  action:
  - type: turn_on
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1689597312837'
  alias: boilerFirstStageOFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_minus05_enel_plus1_solar
    from: 'on'
    to: 'off'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.manualboiler
    state: 'off'
  - condition: state
    entity_id: input_boolean.sunny_day
    state: 'on'
  action:
  - type: turn_off
    device_id: 3ad97e1daf95913698b7b1acb69a32d8
    entity_id: switch.boiler
    domain: switch
  mode: single
- id: '1684411816150'
  alias: mumEnterHome
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.enrica_s_phone
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: d249ac2f4ec0a0c31d54c400d8a07c82
    domain: mobile_app
    type: notify
    message: Mum
  - device_id: ca685c3b3eef896822f021d3153787f6
    domain: mobile_app
    type: notify
    message: Mum enter home
  mode: single
- id: '1684443772730'
  alias: dadEnterHome
  description: ''
  trigger:
  - platform: zone
    entity_id: person.adriano
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: d249ac2f4ec0a0c31d54c400d8a07c82
    domain: mobile_app
    type: notify
    message: Dad
  - device_id: ca685c3b3eef896822f021d3153787f6
    domain: mobile_app
    type: notify
    message: Dad enter home
  mode: single
- id: '1691699008243'
  alias: iPad20PercentTurnON
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: ede330a4d1d8b3aa4ce2a3f7fbf86bb2
    entity_id: ef916e116aeacdcb2b74fedbc315d722
    domain: sensor
    below: 20
  condition:
  - condition: device
    type: is_off
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  action:
  - type: turn_on
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- id: '1691699042947'
  alias: iPad80PercentTurnOFF
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: ede330a4d1d8b3aa4ce2a3f7fbf86bb2
    entity_id: ef916e116aeacdcb2b74fedbc315d722
    domain: sensor
    above: 80
  condition: []
  action:
  - type: turn_off
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- id: '1692911680530'
  alias: camerasDetectionNotification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.garden_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id: sensor.back_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id: sensor.gardensouth_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id:
    - sensor.entrance_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  - platform: numeric_state
    entity_id:
    - sensor.garage_person_count
    for:
      hours: 0
      minutes: 0
      seconds: 1
    above: 0
  condition:
  - condition: state
    entity_id: input_boolean.person_notification
    state: 'on'
  action:
  - device_id: d249ac2f4ec0a0c31d54c400d8a07c82
    domain: mobile_app
    type: notify
    message: 'Camera '
  mode: single
- id: '1692972394716'
  alias: frigateEntranceKito
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.entrance
      base_url: https://xc5oo1paki2zabddex3se0s8lcrq40ho.ui.nabu.casa/
      color: red
      message: Entrance person
      attachment: snapshot
      cooldown: 185
      tap_action: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
      notify_device: d249ac2f4ec0a0c31d54c400d8a07c82
      silence_timer: 8
      disable_times:
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
      - '15'
      - '16'
      - '17'
      - '18'
- id: '1694008677172'
  alias: frigateEntranceDad
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.entrance
      base_url: https://xc5oo1paki2zabddex3se0s8lcrq40ho.ui.nabu.casa/
      color: red
      message: Entrance person
      attachment: snapshot
      cooldown: 185
      tap_action: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
      silence_timer: 8
      notify_device: 3985d73a7a80bc86bc18415055134bf0
      disable_times:
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
      - '15'
      - '16'
      - '17'
      - '18'
      - '19'
      - '20'
- id: '1694041188700'
  alias: entrancePersonInNightLed
  description: 'when entrance camera detect person turn on for 3.14 minutes entrance
    led and lampade out


    v2

    for turn off now wait the trigger below1 person for 3.14 min, so if person reappen,
    it restart the counter of 3.14 min, '
  trigger:
  - type: value
    platform: device
    device_id: 7f18cc52a1f0db774bdf1ab808e3d624
    entity_id: 6d80ff481151fab8778752679f4a3d9a
    domain: sensor
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    after_offset: 0:30
    before_offset: 0:40
  action:
  - type: turn_on
    device_id: 66672ab969f60c7ed08377fb6389511e
    entity_id: 047e93f56340f6def908aa6764919315
    domain: switch
    enabled: false
  - type: turn_on
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: 7af0d52f2f672ccab6a06f04edbc3436
    domain: switch
  - wait_for_trigger:
    - type: value
      platform: device
      device_id: 7f18cc52a1f0db774bdf1ab808e3d624
      entity_id: 6d80ff481151fab8778752679f4a3d9a
      domain: sensor
      below: 1
      for:
        hours: 0
        minutes: 3
        seconds: 14
    timeout:
      hours: 0
      minutes: 3
      seconds: 14
      milliseconds: 0
  - type: turn_off
    device_id: 66672ab969f60c7ed08377fb6389511e
    entity_id: 047e93f56340f6def908aa6764919315
    domain: switch
    enabled: false
  - type: turn_off
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: 7af0d52f2f672ccab6a06f04edbc3436
    domain: switch
  mode: single
- id: '1694689039662'
  alias: batterySecondStageON
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_second_stage
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: state
    entity_id: switch.sw1
    state: 'off'
  - condition: state
    entity_id: switch.sw2
    state: 'off'
  - condition: state
    entity_id: input_boolean.sunny_day
    state: 'on'
  action:
  - type: turn_on
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1694689062167'
  alias: batterySecondStageOFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.combo_second_stage
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.sunny_day
    state: 'on'
  action:
  - type: turn_off
    device_id: 5ba4557ff747bdc01d9581d5c8f35b5e
    entity_id: 99dba97e96242c48f2adcb0b7e1ba24f
    domain: switch
  mode: single
- id: '1695217201945'
  alias: ledBackCameraBackDetect
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: d616f14b47ba4ebec4d453f5e8934b99
    entity_id: 4abfcb69e2524780628c72669905cd2c
    domain: sensor
    above: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: c27acc2ccd63098e7b1bfdc348a38ab8
    domain: switch
  - delay:
      hours: 0
      minutes: 2
      seconds: 14
      milliseconds: 0
  - type: turn_off
    device_id: c2080a4515fda07919d6eb7f4723eddd
    entity_id: c27acc2ccd63098e7b1bfdc348a38ab8
    domain: switch
  mode: single
- id: '81878494'
  alias: fix_temperature2
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.temperature2
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.temperature2
      state: unavailable
    - condition: state
      entity_id: sensor.temperature2
      state: '-127'
  action:
  - service: input_number.set_value
    data:
      value: '{{ states(''sensor.temperature2'') }}'
    target:
      entity_id: input_number.temp2previuous
  mode: single
- id: '1699040422869'
  alias: fix_temperature1
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.temperature1
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.temperature1
      state: unavailable
    - condition: state
      entity_id: sensor.temperature1
      state: '-127'
  action:
  - service: input_number.set_value
    data:
      value: '{{ states(''sensor.temperature1'') }}'
    target:
      entity_id: input_number.temp1previous
  mode: single
- id: '1703958932352'
  alias: fix_temperature3
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.temperatureout
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.temperatureout
      state: unavailable
    - condition: state
      entity_id: sensor.temperatureout
      state: '-127'
  action:
  - service: input_number.set_value
    data:
      value: '{{ states(''sensor.temperatureout'') }}'
    target:
      entity_id: input_number.temp_out_saved
  mode: single
- id: '1705791658846'
  alias: Sw1 lock
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e7b926b9a39fd75d06fd1e9ac4f3e53b
    entity_id: e8c6b1cf6e1e2ff49b7adfccf9018ae0
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_off
    device_id: e7b926b9a39fd75d06fd1e9ac4f3e53b
    entity_id: b07c904f35dccea5a9282516ef5ba4e5
    domain: switch
  mode: single
- id: '1705791700776'
  alias: Sw2 lock
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e7b926b9a39fd75d06fd1e9ac4f3e53b
    entity_id: b07c904f35dccea5a9282516ef5ba4e5
    domain: switch
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - type: turn_off
    device_id: e7b926b9a39fd75d06fd1e9ac4f3e53b
    entity_id: e8c6b1cf6e1e2ff49b7adfccf9018ae0
    domain: switch
  mode: single
- id: '1705869478933'
  alias: SalaOnNorification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.ac_sala_function
    from: 'on'
    to:
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - device_id: d249ac2f4ec0a0c31d54c400d8a07c82
    domain: mobile_app
    type: notify
    message: Sala OFF
  mode: single
- id: '1706191197961'
  alias: ScalaOFF
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.ac_scala_function
    from: 'on'
    to:
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - device_id: d249ac2f4ec0a0c31d54c400d8a07c82
    domain: mobile_app
    type: notify
    message: Scala OFF
  mode: single
- &id001
  id: '1707138230175'
  alias: fanEnelON
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 8a585a7681c4f281e2d461365c509654
    entity_id: b2edf97604ce18c942118213573eadb3
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - type: turn_on
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- id: '1707138266244'
  alias: fanEnelOFF
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 8a585a7681c4f281e2d461365c509654
    entity_id: da79df00c68011fe7de1557d6046adc0
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  action:
  - type: turn_off
    device_id: 1ca0200ea5167c03991934fb8e457480
    entity_id: 7dece757f3e7794530b55a103dd4c7a2
    domain: switch
  mode: single
- *id001
