# CONFIGURATION.YAML
# AUTHOR: kito129

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

# MariaDb configuration
recorder:
  db_url: !secret dbUrl
  purge_keep_days: 365

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# packeges
homeassistant:
  packages: !include_dir_named packages

### YAML file locations
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary.yaml
sensor: !include sensors.yaml
template: !include templates.yaml

# Influx db connection
influxdb:
  host: !secret influxHost
  port: !secret influxPort
  database: !secret influxDatabaseName
  username: !secret influxDatabaseUser
  password: !secret influxPass
  max_retries: 5
  default_measurement: state

# apex-charts resources:
#  - url: /local/apexcharts-card.js?v=2.0.2
#    type: module

# Logger configuration
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning
    custom_components.my_integration: warning
    custom_components.average: warning

# MQTT SENSORS
mqtt:
  sensor:
    # esp32-DF36A0
    ## Sensor 1
    - name: "Temperature1"
      state_topic: "homeassistant/sensor/esp32iotsensor/temperatureSensor"
      value_template: "{{ value_json.temp_1 }}"
      unique_id: "0a7476cc-d6c1-40ba-8ae1-60651843524353425"
      device_class: temperature
      unit_of_measurement: °C
    ## Sensor 2
    - name: "Temperature2"
      state_topic: "homeassistant/sensor/esp32iotsensor/temperatureSensor"
      unique_id: "0a7476cc-d6c1-40ba-8ae1-606518435256736535"
      device_class: temperature
      unit_of_measurement: °C
      value_template: "{{ value_json.temp_2 }}"
      ## Sensor 3
    - name: "Temperatureout"
      state_topic: "homeassistant/sensor/esp32iotsensor/temperatureSensor"
      unique_id: "0a7476cc-d6c1-40ba-8ae1-2828945225"
      device_class: temperature
      unit_of_measurement: °C
      value_template: "{{ value_json.temp_out }}"

# for frigate
ios:
  push:
    categories:
      - name: camera
        identifier: "camera"
        actions:
          - identifier: "SENDSTILLANDCLIP"
            title: "Send still and video clip"
            authenticationRequired: false
# workstationsensor openhardwaremonitor
#openhardwaremonitor:
# - platform: openhardwaremonitor
#   host: http://172.17.144.1

#http:
#  api_password: !secret api_password
#  trusted_proxies: 172.16.0.0/12
#  trusted_networks: 172.16.0.0/12
#  use_x_forwarded_for: true
#  ip_ban_enabled: true
#  login_attempts_threshold: 3

# climate


# BROADLINK

switch:
  - platform: broadlink
    mac: EC:0B:AE:A3:97:E2
    switches:
      - name: Ac_Scala_Wifi_command
        command_on: JgC2AGY2Cw8LKQwODA4MKAwODCgMDgwODCgMKAwpCw8LKQwODCgMKAwoDA4MDgwODA4MKAwpCw8LKQwoDA4MDgwoDA4MDgwoDA4MDgwpCykLDwwoDCgMKAwODCgMDgwoDCkLKQsPDA4MKAwODCgMDgwODA4MKAwoDCkLKQsPDCgMKAwoDA4MDgwODA4MKAwPCw8LDwspDCgMKAwODA4MKAwoDCgMDgwPCw8LKQspDA4MDgwODCgMAA0FAAA=
        command_off: JgC2AGc1DA4MKAwODA4MKQsPCykMDgwODCgMKAwoDA4MKAwODCkLKQspDA4MDgwODA4MKAwoDA4MKAwpCw8LDwspDA4MDgwoDA4MDgwoDCgMDgwpCykLKQwODCgMDgwoDCgMKAwODA4MKQsPCykLDwwODA4MKAwoDCgMKAwODCkLKQspDA4MDgwODA4MKAwODA4MDgwoDCgMKQsPCykMKAwoDCgMDgwODA4MKAwODA8LDwsPCykMAA0FAAA=