# SENSORS.YAML
# AUTHOR: kito129

# *** SYSTEM MONITOR ***
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

# *** TIME AND DATE ***
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

# **** INTEGRATION ****

## CUCINA ENERGY SENSORS

# frigo_forno_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-8882845"
  method: "left"
  source: sensor.oven_power
  name: frigo_forno_energy
  unit_prefix: k
  unit_time: h
  round: 2

# lavastoviglie_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-25828714"
  method: "left"
  source: sensor.washdisher_power
  name: lavastoviglie_energy
  unit_prefix: k
  unit_time: h
  round: 2

## HOME ENERGY SENSORS

# home_loads_energy
- platform: integration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-606518c3497c"
  method: "left"
  source: sensor.home_other_loads_power
  name: home_loads_energy
  unit_prefix: k
  unit_time: h
  round: 2

## BOILER ENERGY SENSORS

# boiler_room_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-6518715"
  method: "left"
  source: sensor.boiler_room_power
  name: boiler_room_energy
  unit_prefix: k
  unit_time: h
  round: 2

# ac_total_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-8787484"
  method: "left"
  source: sensor.ac_total_power
  name: ac_total_energy
  unit_prefix: k
  unit_time: h
  round: 2

# boiler_resistenza_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-58252"
  method: "left"
  source: sensor.boiler_resistance_power
  name: boiler_resistenza_energy
  unit_prefix: k
  unit_time: h
  round: 2

# boiler_pompa_di_calore_energy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-287252"
  method: "left"
  source: sensor.boiler_heat_pump_power
  name: boiler_pompa_di_calore_energy
  unit_prefix: k
  unit_time: h
  round: 2

## INTERNET

##  BATTERY
# battery_in_energy_integral
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-28748565"
  method: "left"
  source: sensor.battery_in_power
  name: battery_in_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2

# battery_out_energy_integral
- platform: integration

  unique_id: "0a7476cc-245654-2456-8ae1-281983"
  method: "left"
  source: sensor.battery_out_power
  name: battery_out_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2

# battery_net_energy_integral
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-984763"
  method: "left"
  source: sensor.battery_net_power
  name: battery_net_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2

# *** AVERAGE **

# POWER

# solarPowerAvg
- platform: statistics
  state_characteristic: mean
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282852"
  name: "solarPowerAvg"
  max_age:
    minutes: 20
  entity_id: sensor.solar_power

# enelPowerAvg
- platform: statistics
  state_characteristic: mean
  name: "enelPowerAvg"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282825"
  max_age:
    minutes: 20
  entity_id: sensor.enel_power

# homePowerAvg
- platform: statistics
  state_characteristic: mean
  name: "homePowerAvg"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282821875"
  max_age:
    minutes: 20
  entity_id: sensor.home_power

# POWER DERIVATE

# enel_derivate_average
- platform: statistics
  state_characteristic: mean
  name: "enelDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282966"
  max_age:
    minutes: 20
  entity_id: sensor.enelDerivate

# solar_derivate_average
- platform: statistics
  state_characteristic: mean
  name: "solarDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-88828288582"
  max_age:
    minutes: 20
  entity_id: sensor.solarDerivate

# home_derivate_average
- platform: statistics
  state_characteristic: mean
  name: "homeDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-88828282545"
  max_age:
    minutes: 20
  entity_id: sensor.homeDerivate

## TEMPERATURE

# temp1
- platform: statistics
  state_characteristic: mean
  name: "outTempAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-8882824565"
  max_age:
    minutes: 20
  entity_id: sensor.temperature1

# temp2
- platform: statistics
  state_characteristic: mean
  name: "ACTempAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-17871874"
  max_age:
    minutes: 20
  entity_id: sensor.temperature2

## *** HISTORY_STATS ***

### BOILER ROOM

# BOILER

# boiler_heat_pump_duration
- platform: history_stats
  name: boiler_heat_pump_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-4847568"
  entity_id: binary_sensor.boiler_pompa_di_calore
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# boiler_resistance_duration
- platform: history_stats
  name: boiler_resistance_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-871745"
  entity_id: binary_sensor.boiler_resistenza
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# boiler_pump_resistance_duration
- platform: history_stats
  name: boiler_pump_resistance_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-5828552"
  entity_id: binary_sensor.boiler_pompa_e_resistenza
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# LAVATRICE

### KITCHEN

# LAVASTOVIGLIE

# frigo_on_duration
- platform: history_stats
  name: frigo_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-28455"
  entity_id: binary_sensor.frigo_state
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

## SOLAR

# 05kWSolar
- platform: history_stats
  name: 05kWSolar_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-25878945"
  entity_id: binary_sensor.plus_05_kw_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# 1kWSolar
- platform: history_stats
  name: 1kWSolar_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-284568"
  entity_id: binary_sensor.plus_1_kw_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# 2kWSolar
- platform: history_stats
  name: 2kWSolar_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-718485"
  entity_id: binary_sensor.plus_2_kw_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# 3kWSolar
- platform: history_stats
  name: 3kWSolar_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-5159552"
  entity_id: binary_sensor.plus_3_kw_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# 4kWSolar
- platform: history_stats
  name: 4kWSolar_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-287187"
  entity_id: binary_sensor.plus_4_kw_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

## MINUS ENEL

# minus00_05kWEnel_on_duration
- platform: history_stats
  name: minus00_05kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-516551220"
  entity_id: binary_sensor.minus_00_05_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# minus05kWEnel
- platform: history_stats
  name: minus05kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-8189489615"
  entity_id: binary_sensor.minus_05_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# minus1kWEnel
- platform: history_stats
  name: minus1kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-717845"
  entity_id: binary_sensor.minus_1_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# minus2kWEnel
- platform: history_stats
  name: minus2kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-2852863863"
  entity_id: binary_sensor.minus_2_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# minus3kWEnel
- platform: history_stats
  name: minus3kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-717863683683845"
  entity_id: binary_sensor.minus_3_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

## PLUS enel

# plus_00_05_kw_enel
- platform: history_stats
  name: plus_00_05_kw_enel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-06652822623"
  entity_id: binary_sensor.plus_00_05_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# plus05kWEnel
- platform: history_stats
  name: plus05kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-7874882"
  entity_id: binary_sensor.plus_05_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# plus1kWEnel
- platform: history_stats
  name: plus1kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-7174787844"
  entity_id: binary_sensor.plus_1_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# plus2kWEnel
- platform: history_stats
  name: plus2kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-sfgbv1sf"
  entity_id: binary_sensor.plus_2_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# plus3kWEnel
- platform: history_stats
  name: plus3kWEnel_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-18845"
  entity_id: binary_sensor.plus_3_kw_enel
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

## STAGE

# comboFirstStage
- platform: history_stats
  name: comboFirstStage_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-51984852"
  entity_id: binary_sensor.combo_minus05_enel_plus1_solar
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# comboSecondStage
- platform: history_stats
  name: comboSecondStage_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-27825282"
  entity_id: binary_sensor.combo_second_stage
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

# comboThirdStage
- platform: history_stats
  name: comboThirdStage_on_duration
  unique_id: "0a7476cc-d6c1-40ba-8ae1-27525"
  entity_id: binary_sensor.combo_third_stage
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
