# SENSORS.YAML
# AUTHOR: kito129

# SYSTEM MONITOR
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

# ENERGY SENSORS

# frigoFornoEnergy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-8882845"
  method: "left"
  source: sensor.oven_power
  name: frigo_forno_energy
  unit_prefix: k
  unit_time: h
  round: 2

# lavastoviglieEnergy
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-25828714"
  method: "left"
  source: sensor.washdisher_power
  name: lavastoviglie_energy
  unit_prefix: k
  unit_time: h
  round: 2

# INTERNET

  # DATA IN INTERNET Mbps
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-28452"
  method: "left"
  source: sensor.upnp_igd_kib_s_received
  name: internet_data_in_integral
  unit_time: h
  round: 2
  
  # DATA OUT INTERNET Mbps
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-28453"
  method: "left"
  source: sensor.upnp_igd_kib_s_sent
  name: internet_data_out_integral
  unit_time: h
  round: 2


# BATTERY

  # BATTERY IN
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-28748565"
  method: "left"
  source: sensor.battery_in_power
  name: battery_in_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2

  # BATTERY OUT
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-281983"
  method: "left"
  source: sensor.battery_out_power
  name: battery_out_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2
  
  # BATTERY NET
- platform: integration
  unique_id: "0a7476cc-245654-2456-8ae1-984763"
  method: "left"
  source: sensor.battery_net_power
  name: battery_net_energy_integral
  unit_prefix: k
  unit_time: h
  round: 2

# AVERAGES

  # POWER
- platform: average
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282852"
  name: "solarPowerAvg"
  duration:
    minutes: 20
  entities:
    - sensor.solar_power

- platform: average
  name: "enelPowerAvg"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282825"
  duration:
    minutes: 20
  entities:
    - sensor.enel_power

- platform: average
  name: "homePowerAvg"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282821875"
  duration:
    minutes: 20
  entities:
    - sensor.home_power

# POWER DERIVATE
- platform: average
  name: "enelDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-888282966"
  duration:
    minutes: 20
  entities:
    - sensor.enelDerivate

- platform: average
  name: "solarDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-88828288582"
  duration:
    minutes: 20
  entities:
    - sensor.solarDerivate

- platform: average
  name: "homeDerivateAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-88828282545"
  duration:
    minutes: 20
  entities:
    - sensor.homeDerivate

# TEMPERATURE
- platform: average
  name: "outTempAverage"
  unique_id: "0a7476cc-d6c1-40ba-8ae1-8882824565"
  duration:
    minutes: 20
  entities:
    - sensor.temperature1

# TIME AND DATE

# WASHER END TIME
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'